= Требования к проектам

== Project with Jakarta EE

=== Функциональные части

* Слой базы данных:
** сущности (Entities)
** DAOs (Data Access Objects)
* Слой сервисов.
* Презентационный слой:
** Сервлеты.
** JSP.

=== Требования к слоям

* Организацию соединения с базой данных вынести в отдельный класс, метод которого возвращает соединение.
* Каждый сервис в слое сервисов должен быть реализован с помощью паттерна Singleton.
* Информация в базе данных должна храниться в нормализованном виде.

=== Дополнительные требования

* Реализовать функцию переключения языков в системе.
* В системе обязательно должно присутствовать формирование файла (отчёт, статистика и т.д.), который пользователь может скачать с сайта.
* В системе должна быть реализована функция логина с помощью адреса почты и пароля.
* Должна быть реализована авторизация пользователя (набор ролей с соответствующими защищёнными страницами).
* Если пользователь не вошёл в систему, содержимое сайта должно быть недоступно (перебрасывать на страницу логина). Реализовать возможность выхода из системы.

== Project with Spring and Hibernate

=== Общие требования

* Проект состоит из двух независимых сервисов, которые в свою очередь имеют много-модульную структуру:
** `web` - сервис для server-side rendering
*** `rest-client` - модуль содержащий REST clients для запросов в другие REST сервисы.
*** `mvc` - модуль содержащий templates и отвечающий за генерацию web-pages.
** `rest-api`
*** `api` - модуль с описанием REST API сервиса
*** `impl` - модуль с реализацией REST API
*** `dal` - модуль для работы с данными
* Сборка проекта должна осуществляться средствами *Apache Maven*.
* Проект представляет собой *Spring Web* или *Spring Boot* приложение.
* Миграция данных должна осуществляться по средствам *Liquibase*
* Использование *Spring Security* в для аутентификации и авторизации в системе
* Наличие роли администратора, а также наличие доступных лишь администратору возможностей.
* Покрытие кода unit-тестами не менее 80%.
* Поддержка работы с кириллицей.

=== Требования к модулю `dal`

* В качестве RDBMS использовать *PostgreSQL*.
* В качестве ORM использовать *Hibernate*.
* Использование кэша второго уровня *Hibernate*.
* Полная транзакционность, обеспечиваемая за счет интеграции *Hibernate* и *Spring*.
* Использование *Spring Data* для создания запросов.
* Не менее 6 значимых сущностей (`@Entity`).
* `GenericDao` – параметризованный класс с конкретными реализациями – наследниками.
* Пароля пользователя хранится в зашифрованном виде.
* Наличие:
** связей: `1-1`, `1-n`, `n-n`.
** Embedded-сущностей.
** наследования в сущностях.
** оптимистической блокировки сущности.
** запросов с ограничением выборки (пагинация).

=== Требования к модулю `impl`

* Наличие логирования (`log4j2`), запись в файл.
* Часть логирования осуществлять с помощью аспектов Spring.

=== Требования к модулю `mvc`

* Для реализации слоя представления использовать связку *Spring MVC* + *Thymeleaf*.
* Реализовать возможность редактирования сущности на странице с учётом оптимистической блокировки.
* GUI должен представлять собой полноценное web-приложение с не менее чем 10-ю веб-страницами, логически связанных между собой.
* Реализовать интернационализацию, используя Spring.
* Обязательно реализовать страницы:
** регистрации пользователя
** с пагинацией
** для редактирования сущности с возможностью редактирования несколькими пользователями одновременно для демонстрации оптимистической блокировки.
