= Stage 04: Инициализация maven-проекта

На этом этапе создает Apache Maven проекта в рамках которого будет выполняться разработка. В процессе разработки может происходить:

* Декомпозиция проекта на модули
* Декомпозиция проекта на независимые модули (сервисы)
* Изменение используемых libraries, tools, stack

NOTE: Для независимых сервисов, чаще всего, практикуют подход *One repository per One service*. В данном случае он не практикуется, так как это усложнит разработку.

== Tasks

* Инициализировать web-application с помощью Apache Maven.
* Создать общедоступную страницу с проектом, которая содержит приветствие для потенциальных клиентов.

WARNING: Разработку нового функционала можно считать завершенной, если он доступен для конечных пользователей, т.е. недостаточно разработать source code и отправить его в repository, необходимо развернуть приложение на максимально доступном окружении. Для собственных проектов — это *PROD*, для проектов на outsource - это скорее всего *DEV* (или другие, в зависимости от процесса).

== Example

* link:http://ec2-3-71-2-193.eu-central-1.compute.amazonaws.com:8080/ih/[Interview Helper as web-application^]
* link:https://github.com/JD2-86/interview-helper[Interview Helper as project^]
