= Stage 05: Разработка Data Access Layer

На этом этапе создает *Data Access Layer* (*слой доступа к данным*) для приложения, который будет обеспечивать приложение данными.

== Tasks

WARNING: В процессе реализации допускается изменение *Domain models*, хотя это говорит о ее недостаточной проработке на более ранних этапах.

* Реализовать *Domain models* как Java classes.
* На базе *User Stories* необходимо выделить *Domain models* над которыми будут производиться какие-либо операции и сами операции.
* Создать *DAO* interface для каждой *Domain Models* выделенной на предыдущем этапе.
* Создать и описать методы в *DAO* interfaces.
* Реализовать *DAO* interfaces. Для этого можно использовать тот способ, который доступен на данный момент. Например:
** *Java Collection Framework* для хранения в оперативной памяти
** *Files and IO Streams* для хранения в файловой системе
** *JDBC* для хранения в БД
** Прочие библиотеки или фреймворки
* Мигрировать в хранилище данные (необходимо для демонстрации работы)
* Протестировать работу *DAO*.

== Example

* link:https://github.com/JD2-86/interview-helper[Interview Helper as project^]
